language: node_js
node_js:
  - "6"
branches:
  only:
    - master
before_install:
  - git config --global user.email "hartwick.abigail@gmail.com"
  - git config --global user.name "Abi Morris"
after_success:
  - npm install -g gh-pages
  - npm install
  - npm run pre:build
  - npm run build
  - npm run build:deploy
