# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Recipes
tagline:          'Wholesome Eating!'
description:      'Some of the tastiest wholesome healthy recipes around.'
url:              abugail.github.io/recipes
baseurl:          /recipes
# Travis will install Bundler dependencies in ./vendor, so we need to exclude it
# otherwise Jekyll will try to build it (and fail)
exclude:          [vendor]

author:
  name:           'Abigail Morris'
  url:            http://abugail.github.com/recipes
# Thanks to @mdo for the original theme
# author:
#   name:           'Mark Otto'
#   url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
    repo:         https://github.com/abugail/recipes

# Algolia
gems:
  - algoliasearch-jekyll

algolia:
  application_id: '8TZNCU1121'
  index_name: 'recipes'
  read_only_api_key: '9a672277762357d9c720b64e6e40fd98'
  excluded_files:
    - 404.html
    - index.html
